### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by fabre-thibaud** [aztech-digital/phinject#3]
Documentation is currently behind actual features.
# Tasks
- [ ] Document all reference syntaxes and features
- [ ] Document command line tools
- [ ] Document best practices
